### ISSUE TITLE
help

### ISSUE THREAD

**Issue by workaholicwjj** [pykt-team/pykt-toolkit#131]
2023-09-19 00:37:50 - main - said: init_model
model_name:sparsekt
The wrong model name was used...
model is None
Traceback (most recent call last):
  File "wandb_sparsekt_train.py", line 39, in <module>
    main(params)
  File "/root/pykt-toolkit-main/examples/wandb_train.py", line 123, in main
    opt = Adam(model.parameters(), learning_rate)
AttributeError: 'NoneType' object has no attribute 'parameters'

**Comment by workaholicwjj** [comment]
使用sparseKT模型就会显示这个问题可能是什么原因？

**Comment by sonyawong** [comment]
> 使用sparseKT模型就会显示这个问题可能是什么原因？

hi, 方便的话您可以提供一下运行命令吗？

**Comment by workaholicwjj** [comment]
我刚接触这个不是很懂，在乌班图环境下，进入examples，运行指令python wandb_sparsekt_train.py就会这个问题，其他试了几个sakt，akt都行的

**Comment by sonyawong** [comment]
> 我刚接触这个不是很懂，在乌班图环境下，进入examples，运行指令python wandb_sparsekt_train.py就会这个问题，其他试了几个sakt，akt都行的

您用的是main分支下的代码吗

**Comment by workaholicwjj** [comment]
是的默认下载就是哪个

**Comment by lycyhrc** [comment]
> 2023-09-19 00:37:50 - main - said: init_model
> 
> model_name:sparsekt
> 
> The wrong model name was used...
> 
> model is None
> 
> Traceback (most recent call last):
> 
>   File "wandb_sparsekt_train.py", line 39, in <module>
> 
>     main(params)
> 
>   File "/root/pykt-toolkit-main/examples/wandb_train.py", line 123, in main
> 
>     opt = Adam(model.parameters(), learning_rate)
> 
> AttributeError: 'NoneType' object has no attribute 'parameters'

这里要运行代码，需要将项目根目录添加到 pythonpath 中：

`export PYTHONPATH="${PYTHONPATH}:/path/.../pykt-toolkit" `

**Comment by MYLITEHEART** [comment]
您好，我添加完目录之后执行这行代码

> CUDA_VISIBLE_DEVICES=0 python wandb_atdkt_train.py --dataset_name=algebra2005 --use_wandb=0 --add_uuid=0 --num_attn_heads=2 > atdkt_train.txt

之后还是会报同样的错误

> File "wandb_atdkt_train.py", line 31, in <module>
>     main(params)
>   File "/home/abel/下载/codes/pykt-toolkit-main/examples/wandb_train.py", line 128, in main
>     opt = Adam(model.parameters(), learning_rate)
> AttributeError: 'NoneType' object has no attribute 'parameters'

请问是什么原因？

**Comment by lycyhrc** [comment]
> 您好，我添加完目录之后执行这行代码
> 
> > CUDA_VISIBLE_DEVICES=0 python wandb_atdkt_train.py --dataset_name=algebra2005 --use_wandb=0 --add_uuid=0 --num_attn_heads=2 > atdkt_train.txt
> 
> 之后还是会报同样的错误
> 
> > File "wandb_atdkt_train.py", line 31, in 
> > main(params)
> > File "/home/abel/下载/codes/pykt-toolkit-main/examples/wandb_train.py", line 128, in main
> > opt = Adam(model.parameters(), learning_rate)
> > AttributeError: 'NoneType' object has no attribute 'parameters'
> 
> 请问是什么原因？

https://github.com/pykt-team/pykt-toolkit/issues/209#issuecomment-2472153459 请参考这个回答，一般来说，修改后在path/.../pykt-toolkit下执行 pip install -e . 可以解决这个问题
